### PR TITLE
Update IdealGasLawCalc.py

### PR DESCRIPTION
**Pull request by WarpWing**
Hmmmm

### CODE REVIEW

**Comment by EnderBro1000** [comment]
What did you do?

**Comment by WarpWing** [comment]
You should be able to see it. Look in "Files Changed"

**Comment by EnderBro1000** [comment]
I looked, and i couldnt tell, it looked like you replaced some lines with the exact same words. In the future, actually say what you changed.

**Comment by WarpWing** [comment]
I changed Capitalization. Improper vs improper. It bothered me xd

**Comment by EnderBro1000** [comment]
Oh, ok

**Pull request merged**
